(()=>{"use strict";
const KEY="ordem_threats";
const skillNames=["Manobra","Disciplina","Especialização","Discreto","Interação","Fortitude","Intimidação","Dedução","Luta","Medicina","Ocultismo","Percepção","Pilotagem","Pontaria","Presteza","Sobrevivência","Informação","Vontade","Sorte"];
const wolfSkills={Manobra:2,Discreto:2,Fortitude:2,Intimidação:2,Luta:2,Presteza:3,Percepção:3};
let threats=[],editingId=null,type="creature",normalPhoto="",woundedPhoto="",abilitiesDraft=[];
const ENEMY_ABILITY_CATALOG=[
 {id:"investida",name:"Investida",description:"Após se mover, pode receber +1 dado de dano no próximo ataque. Requer movimento e só pode ser usada 1 vez por rodada.",trigger:"after-move",oncePerRound:true},
 {id:"mordida-feroz",name:"Mordida Feroz",description:"Após acertar um Ataque Forte, disputa Manobra contra o alvo. Se vencer, aplica Caído até o alvo vencer uma nova disputa de Manobra. Uso: 1 vez a cada 2 rodadas.",trigger:"strong-hit",cooldownRounds:2},
 {id:"esquiva-maior",name:"Esquiva Maior",description:"Ao usar Esquiva, dobra a RD. Uso: 1 vez por rodada e no máximo Corpo vezes por cena.",trigger:"dodge",oncePerRound:true,usesPerSceneAttribute:"corpo"}
 ,{id:"reliquia",name:"Relíquia",description:"Dobra o PV clássico e o PV máximo de todos os membros.",passive:true}
 ,{id:"toque-da-morte",name:"Toque da Morte",description:"Sempre que sofre um ataque realizado com Luta, o atacante envelhece 3 anos.",passive:true}
 ,{id:"possessao",name:"Possessão",description:"Gasta 1 PA em um alvo morto para invocar um Morto-vivo. Usos por cena iguais a Nexo.",paCost:1,usesPerSceneAttribute:"nexo"}
 ,{id:"agarrao-necrotico",name:"Agarrão Necrótico",description:"Uma vez a cada 2 rodadas, disputa Manobra contra o alvo. Se vencer, aplica Paralisia até o alvo vencer Manobra ou ser solto.",cooldownRounds:2}
 ,{id:"apice-do-poder",name:"Ápice do Poder",description:"Imune a dano e efeitos de rituais do mesmo elemento principal da ameaça.",passive:true}
 ,{id:"cronos",name:"Cronos",description:"Uma vez por cena, recebe +3 PA na rodada atual.",oncePerScene:true}
 ,{id:"invocador",name:"Invocador",description:"Gasta 2 PA para trazer uma criatura de até NV 5 ao combate. Usos por cena iguais a Nexo.",paCost:2,usesPerSceneAttribute:"nexo"}
 ,{id:"segunda-fase",name:"Segunda Fase",description:"Ao adquirir Machucado, recebe +1 dado no dano principal dos ataques básico e forte e +3 para acertar.",passive:true}
 ,{id:"camada-extra",name:"Camada Extra",description:"Recebe +3 de RD total.",passive:true}
 ,{id:"conjurador",name:"Conjurador",description:"Permite conjurar rituais e utilizar o grimório.",passive:true}
 ,{id:"ferocidade",name:"Ferocidade",description:"Adiciona +1 dado de dano principal aos ataques básico e forte.",passive:true}
 ,{id:"atrair",name:"Atrair",description:"Disputa Vontade contra um alvo. Se vencer, o alvo avança até a posição 1. Uso: 1 vez a cada 2 rodadas.",cooldownRounds:2}
 ,{id:"ilusorio",name:"Ilusório",description:"Assume a aparência de alguém importante para o alvo. O alvo sofre penalidade no próximo ataque igual ao Nexo da ameaça. Uso: 1 vez por rodada.",oncePerRound:true}
 ,{id:"regenerativo",name:"Regenerativo",description:"No início de cada rodada, recupera PV igual a Corpo. No sistema de membros, regenera o membro mais danificado.",passive:true}
 ,{id:"vampirismo",name:"Vampirismo",description:"Sempre que acerta um ataque, recupera 1d10 PV. No sistema de membros, regenera o membro mais danificado.",passive:true}
 ,{id:"aplicador",name:"Aplicador",description:"Ao deixar um alvo Morrendo, aplica uma condição pelo elemento: Sangue = Sangramento, Morte = Envenenamento, Energia = Chamas, Conhecimento = Vulnerável.",passive:true}
 ,{id:"espinhoso",name:"Espinhoso",description:"Sempre que sofre um ataque, causa ao atacante dano igual ao Corpo.",passive:true}
];
const wolfAbilities=ENEMY_ABILITY_CATALOG;
const $=id=>document.getElementById(id),num=id=>Math.max(0,Number($(id)?.value)||0);
function load(){try{threats=JSON.parse(localStorage.getItem(KEY)||"[]");if(!Array.isArray(threats))threats=[]}catch{threats=[]}seedWolf()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(threats));return true}catch(error){console.error("Erro ao salvar ameaças:",error);alert("Não foi possível salvar as fotos. Tente imagens menores ou remova imagens antigas.");return false}}
function stats(na){na=Math.max(0,na|0);return{pv:20*(na+1),rd:2*(na+1),defense:5+2*na,attr:2*(na+1),skillBudget:4+2*na,pa:3+Math.floor(na/3),head:4*(na+1),torso:4*(na+1),limb:3*(na+1),movement:2}}
function damage(na,strong=false){let dice;if(na===0)dice="1d4";else if(na===1)dice="1d6";else if(na===2)dice="1d8";else if(na===3)dice="1d10";else if(na===4)dice="1d12";else{const extra=4+2*(na-4);dice="1d12 + 1d"+extra}if(strong)dice=dice.replace(/1d(\d+)/g,"2d$1");return dice+" + Corpo"}
function wolf(){const s=stats(6);return{id:"lobisomem-pronto",systemId:"lobisomem-na6",preset:true,type:"creature",name:"Lobisomem",na:6,element:"Morte",size:2,corpo:6,foco:5,nexo:3,skills:{...wolfSkills},abilities:wolfAbilities.map(x=>({...x})),...s,basicAttack:damage(6),strongAttack:damage(6,true),strongAttackLimit:"1/rodada",healthMode:"choice",photo:"",woundedPhoto:""}}
function deathGod(){const s=stats(10),ids=["reliquia","toque-da-morte","possessao","agarrao-necrotico","apice-do-poder","cronos","invocador","segunda-fase","camada-extra","conjurador"];return{id:"deus-da-morte-pronto",systemId:"deus-da-morte-na10",preset:true,type:"creature",name:"Deus da Morte",na:10,element:"Morte",size:3,corpo:8,foco:8,nexo:6,skills:{Manobra:3,Fortitude:3,Intimidação:3,Luta:3,Ocultismo:3,Percepção:3,Presteza:2,Sobrevivência:2,Vontade:2},abilities:ids.map(id=>({...ENEMY_ABILITY_CATALOG.find(a=>a.id===id)})),...s,pv:s.pv*2,head:s.head*2,torso:s.torso*2,limb:s.limb*2,rd:s.rd+3,basicAttack:damage(10),strongAttack:damage(10,true),strongAttackLimit:"1/rodada",healthMode:"choice",passiveStatsApplied:true,photo:"",woundedPhoto:""}}
function seedPreset(build){const ready=build(),i=threats.findIndex(x=>x.systemId===ready.systemId);if(i<0)threats.unshift(ready);else threats[i]={...threats[i],...ready,photo:threats[i].photo||"",woundedPhoto:threats[i].woundedPhoto||""}}
function seedWolf(){seedPreset(wolf);seedPreset(deathGod);save()}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function rank(v){return ["Destreinado","Treinado • 1d4","Veterano • 1d8","Especialista • 1d12"][Number(v)||0]}
function render(q=""){const root=$("enemyList"),term=q.trim().toLowerCase(),list=threats.filter(x=>!term||x.name.toLowerCase().includes(term)||String(x.element||x.npcRole||"").toLowerCase().includes(term));if(!list.length){root.innerHTML='<div class="empty-enemies"><div class="icon">◇</div><h3>Nenhum registro encontrado</h3><p>Crie uma ameaça ou NPC para começar.</p></div>';return}root.innerHTML=list.map(x=>{const npc=x.type==="npc",human=x.type==="human",role={combat:"Combate",support:"Suporte",investigative:"Investigativo"}[x.npcRole]||"Aliado";return'<article class="enemy-card" data-element="'+esc(x.element||"")+'"><div class="enemy-photo">'+(x.photo?'<img src="'+x.photo+'" alt="">':'<span>'+(npc?"♟":human?"👤":"👹")+'</span>')+'</div><div class="enemy-info"><h2>'+esc(x.name)+'</h2><p>'+(npc?"NPC Aliado • "+role+" • Nível "+x.npcLevel:human?"Ameaça Humana":esc(x.element)+" • NA "+x.na+" • Tamanho "+x.size)+'</p><p>'+(npc?x.pv+" PV • 1 ajuda/ação por rodada":x.pv+" PV • DEF "+x.defense+" • RD "+x.rd+" • "+x.pa+" PA • MOV "+x.movement)+'</p></div><div class="enemy-buttons"><button class="edit-button" data-view="'+x.id+'">'+(x.preset?"Ver ficha":"Editar")+'</button></div></article>'}).join("")}
function skillOptions(attribute){return skillNames.map(n=>'<label>'+n+'<select '+attribute+'="'+n+'"><option value="0">Destreinado</option><option value="1">Treinado • 1d4</option><option value="2">Veterano • 1d8</option><option value="3">Especialista • 1d12</option></select></label>').join("")}
function buildSkills(){$("enemySkills").innerHTML=skillOptions("data-skill");$("humanSkills").innerHTML=skillOptions("data-human-skill")}
function abilityId(name,index){const slug=String(name||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");return slug||"habilidade-"+(index+1)}
function renderAbilitySlots(readonly=false){const root=$("enemyAbilities");if(!root)return;if(!abilitiesDraft.length){root.innerHTML='<div class="enemy-ability-readonly"><p>Nenhuma habilidade adicionada.</p></div>';return}root.innerHTML=abilitiesDraft.map((ability,index)=>readonly?'<div class="enemy-ability-readonly"><strong>'+esc(ability.name||"Habilidade")+'</strong><p>'+esc(ability.description||"")+'</p></div>':'<div class="enemy-ability-slot" data-ability-index="'+index+'"><input class="enemy-ability-name" value="'+esc(ability.name||"")+'" placeholder="Nome da habilidade"><textarea class="enemy-ability-description" placeholder="Descrição e regra">'+esc(ability.description||"")+'</textarea><button type="button" class="danger-button enemy-ability-remove">Remover</button></div>').join("");if(readonly)return;root.querySelectorAll(".enemy-ability-slot").forEach(slot=>{const index=Number(slot.dataset.abilityIndex),name=slot.querySelector(".enemy-ability-name"),description=slot.querySelector(".enemy-ability-description");name.oninput=()=>{abilitiesDraft[index].name=name.value;abilitiesDraft[index].id=abilityId(name.value,index)};description.oninput=()=>abilitiesDraft[index].description=description.value;slot.querySelector(".enemy-ability-remove").onclick=()=>{abilitiesDraft.splice(index,1);renderAbilitySlots(false)}})}
function addAbilityFromCatalog(id){const ability=ENEMY_ABILITY_CATALOG.find(item=>item.id===id);if(!ability)return;abilitiesDraft.push({...ability});renderAbilitySlots(false)}
function openAbilityPicker(){document.getElementById("enemyAbilityPicker")?.remove();const modal=document.createElement("div");modal.id="enemyAbilityPicker";modal.className="enemy-modal";modal.innerHTML='<div class="enemy-editor ability-library-dialog"><div class="enemy-editor-head"><div><span>BIBLIOTECA</span><h2>Adicionar habilidade</h2></div><button type="button" class="enemy-close ability-picker-close">✕</button></div><div class="enemy-ability-library">'+ENEMY_ABILITY_CATALOG.map(ability=>'<button type="button" class="enemy-ability-library-card" data-library-ability="'+esc(ability.id)+'"><strong>'+esc(ability.name)+'</strong><span>'+esc(ability.description)+'</span></button>').join("")+'<button type="button" class="enemy-ability-library-card custom" data-custom-ability="true"><strong>Habilidade personalizada</strong><span>Crie uma habilidade nova com nome e descrição próprios.</span></button></div></div>';document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector(".ability-picker-close").onclick=close;modal.onclick=event=>{if(event.target===modal)close()};modal.querySelectorAll("[data-library-ability]").forEach(button=>button.onclick=()=>{addAbilityFromCatalog(button.dataset.libraryAbility);close()});modal.querySelector("[data-custom-ability]").onclick=()=>{abilitiesDraft.push({id:"habilidade-"+(abilitiesDraft.length+1),name:"",description:""});renderAbilitySlots(false);close()}}
function addAbilitySlot(){openAbilityPicker()}
function refresh(){const na=num("enemyNA"),s=stats(na),used=num("enemyCorpo")+num("enemyFoco")+num("enemyNexo"),su=[...document.querySelectorAll("[data-skill]")].reduce((a,e)=>a+Number(e.value||0),0);$("enemyAutoStats").innerHTML='<b>'+s.pv+'</b><small>PV clássico</small><b>'+s.defense+'</b><small>Defesa</small><b>'+s.rd+'</b><small>RD mundana</small><b>'+s.pa+'</b><small>PA</small><b>'+s.head+'</b><small>Cabeça</small><b>'+s.torso+'</b><small>Torso</small><b>'+s.limb+'</b><small>Cada braço/perna</small><b>2</b><small>Movimento</small>';$("attributeBudget").textContent=used+"/"+s.attr+" pontos";$("skillBudget").textContent=su+"/"+s.skillBudget+" pontos";$("attributeBudget").classList.toggle("over",used>s.attr);$("skillBudget").classList.toggle("over",su>s.skillBudget);$("basicAttack").textContent=damage(na);$("strongAttack").textContent=damage(na,true)+" • 1×/rodada"}
function setType(v){type=v;document.querySelectorAll(".enemy-type").forEach(b=>b.classList.toggle("active",b.dataset.type===v));$("creatureEditor").classList.toggle("hidden",v!=="creature");$("humanEditor").classList.toggle("hidden",v!=="human");$("npcEditor").classList.toggle("hidden",v!=="npc")}
function refreshNpcSummary(){const level=Math.max(1,Math.min(3,num("npcLevel"))),die=[0,4,8,12][level];$("npcSummary").innerHTML=`<b>${level*25}</b><small>PV clássico</small><b>1d12 + 1d${die} + ${level*2}</b><small>Ataque</small><b>${level}d8 + ${level*2}</b><small>Dano</small><b>1</b><small>Ajuda/ação por rodada</small>`}
function setPhotoPreview(id,value,icon,label){$(id).innerHTML=value?'<img src="'+value+'" alt="">':'<span>'+icon+'</span><small>'+label+'</small>'}
function resetHumanFields(){$("humanName").value="";[["humanSize",1],["humanMovement",2],["humanPA",3],["humanPV",20],["humanDefense",10],["humanRD",0],["humanCorpo",1],["humanFoco",1],["humanNexo",1],["humanHead",10],["humanTorso",10],["humanLimb",10]].forEach(([id,value])=>{$(id).value=value});$("humanBasicAttack").value="1d6 + Corpo";$("humanStrongAttack").value="2d6 + Corpo";document.querySelectorAll("[data-human-skill]").forEach(e=>e.value=0)}
function reset(){editingId=null;normalPhoto="";woundedPhoto="";abilitiesDraft=[];$("enemyModalTitle").textContent="Nova Ameaça";$("enemyName").value="";$("enemyNA").value=0;$("enemyElement").value="Sangue";$("enemySize").value=1;$("enemyCorpo").value=0;$("enemyFoco").value=0;$("enemyNexo").value=0;document.querySelectorAll("[data-skill]").forEach(e=>e.value=0);resetHumanFields();$("npcName").value="";$("npcRole").value="combat";$("npcLevel").value=1;document.querySelectorAll("#creatureEditor input,#creatureEditor select").forEach(e=>e.disabled=false);$("addEnemyAbility").classList.remove("hidden");["deleteEnemy","deleteHuman","deleteNpc"].forEach(id=>$(id).classList.add("hidden"));$("saveEnemy").classList.remove("hidden");$("saveEnemy").textContent="Salvar criatura";setPhotoPreview("enemyPhotoPreview","","👹","Foto normal");setPhotoPreview("enemyWoundedPhotoPreview","","👹","Foto machucada");setPhotoPreview("humanPhotoPreview","","👤","Foto normal");setPhotoPreview("humanWoundedPhotoPreview","","👤","Foto machucada");setPhotoPreview("npcPhotoPreview","","♟","Foto do NPC");renderAbilitySlots(false);setType("creature");refresh();refreshNpcSummary()}
function open(id,initialType="creature"){reset();if(id){const x=threats.find(t=>String(t.id)===String(id));if(!x)return;editingId=x.id;normalPhoto=x.photo||"";woundedPhoto=x.woundedPhoto||"";abilitiesDraft=Array.isArray(x.abilities)?x.abilities.map(ability=>({...ability})):[];$("enemyModalTitle").textContent=x.preset?x.name:"Editar "+x.name;setType(x.type||"creature");if(x.type==="creature"){$("enemyName").value=x.name;$("enemyNA").value=x.na;$("enemyElement").value=x.element;$("enemySize").value=x.size;$("enemyCorpo").value=x.corpo;$("enemyFoco").value=x.foco;$("enemyNexo").value=x.nexo;document.querySelectorAll("[data-skill]").forEach(e=>e.value=x.skills?.[e.dataset.skill]||0);setPhotoPreview("enemyPhotoPreview",normalPhoto,"👹","Foto normal");setPhotoPreview("enemyWoundedPhotoPreview",woundedPhoto,"👹","Foto machucada");renderAbilitySlots(Boolean(x.preset));refresh();if(x.preset){document.querySelectorAll("#creatureEditor input:not([type=file]),#creatureEditor select").forEach(e=>e.disabled=true);$("addEnemyAbility").classList.add("hidden");$("saveEnemy").classList.remove("hidden");$("saveEnemy").textContent="Salvar fotos";$("deleteEnemy").classList.add("hidden")}}else if(x.type==="npc"){$("npcName").value=x.name||"";$("npcRole").value=x.npcRole||"combat";$("npcLevel").value=x.npcLevel||1;setPhotoPreview("npcPhotoPreview",normalPhoto,"♟","Foto do NPC");refreshNpcSummary()}else fillHuman(x);if(!x.preset){if(x.type==="human")$("deleteHuman").classList.remove("hidden");else if(x.type==="npc")$("deleteNpc").classList.remove("hidden");else $("deleteEnemy").classList.remove("hidden")}}else{setType(initialType);$("enemyModalTitle").textContent=initialType==="npc"?"Novo NPC Aliado":initialType==="human"?"Nova Ameaça Humana":"Nova Ameaça"}$("enemyModal").classList.remove("hidden")}
function fillHuman(x={}){$("humanName").value=x.name||"";[["humanSize",x.size??1],["humanMovement",x.movement??2],["humanPA",x.pa??3],["humanPV",x.pv??20],["humanDefense",x.defense??10],["humanRD",x.rd??0],["humanCorpo",x.corpo??1],["humanFoco",x.foco??1],["humanNexo",x.nexo??1],["humanHead",x.head??10],["humanTorso",x.torso??10],["humanLimb",x.limb??10]].forEach(([id,value])=>{$(id).value=value});$("humanBasicAttack").value=x.basicAttack||"1d6 + Corpo";$("humanStrongAttack").value=x.strongAttack||"2d6 + Corpo";document.querySelectorAll("[data-human-skill]").forEach(e=>e.value=x.skills?.[e.dataset.humanSkill]||0);setPhotoPreview("humanPhotoPreview",x.photo||"","👤","Foto normal");setPhotoPreview("humanWoundedPhotoPreview",x.woundedPhoto||"","👤","Foto machucada")}
function fileToData(input,cb){const f=input.files?.[0];if(!f)return;if(f.size>5*1024*1024){alert("A imagem é muito grande. Use uma imagem de até 5 MB.");input.value="";return}const r=new FileReader;r.onerror=()=>alert("Não foi possível ler a imagem.");r.onload=()=>{const image=new Image;image.onerror=()=>alert("A imagem selecionada é inválida.");image.onload=()=>{const scale=Math.min(1,700/image.width,900/image.height),width=Math.max(1,Math.round(image.width*scale)),height=Math.max(1,Math.round(image.height*scale)),canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const context=canvas.getContext("2d");if(!context){alert("Não foi possível processar a imagem.");return}context.drawImage(image,0,0,width,height);cb(canvas.toDataURL("image/webp",.78))};image.src=r.result};r.readAsDataURL(f)}
function persist(){if(type==="human")return persistHuman();const old=threats.find(x=>String(x.id)===String(editingId));if(old?.preset){const beforePhoto=old.photo,beforeWoundedPhoto=old.woundedPhoto;old.photo=normalPhoto;old.woundedPhoto=woundedPhoto;if(!save()){old.photo=beforePhoto;old.woundedPhoto=beforeWoundedPhoto;return}render($("searchEnemy").value);$("enemyModal").classList.add("hidden");return}const na=num("enemyNA"),s=stats(na),attrs=num("enemyCorpo")+num("enemyFoco")+num("enemyNexo"),skills={};document.querySelectorAll("[data-skill]").forEach(e=>skills[e.dataset.skill]=Number(e.value||0));const st=Object.values(skills).reduce((a,b)=>a+b,0);if(attrs>s.attr)return alert("Atributos excedem o limite de "+s.attr+" pontos.");if(st>s.skillBudget)return alert("Perícias excedem o limite de "+s.skillBudget+" pontos.");const abilities=abilitiesDraft.filter(ability=>String(ability.name||"").trim()).map((ability,index)=>({...ability,id:abilityId(ability.name,index),name:String(ability.name).trim(),description:String(ability.description||"").trim()}));const x={...(old||{}),id:editingId||"threat-"+Date.now(),preset:false,type:"creature",name:$("enemyName").value.trim()||"Criatura",na,element:$("enemyElement").value,size:Math.max(1,num("enemySize")),corpo:num("enemyCorpo"),foco:num("enemyFoco"),nexo:num("enemyNexo"),skills,abilities,...s,basicAttack:damage(na),strongAttack:damage(na,true),strongAttackLimit:"1/rodada",healthMode:"choice",photo:normalPhoto,woundedPhoto};store(old,x)}
function persistHuman(){const old=threats.find(x=>String(x.id)===String(editingId)),skills={};document.querySelectorAll("[data-human-skill]").forEach(e=>skills[e.dataset.humanSkill]=Number(e.value||0));const x={...(old||{}),id:editingId||"human-threat-"+Date.now(),preset:false,type:"human",element:"Humano",name:$("humanName").value.trim()||"NPC",size:Math.max(1,num("humanSize")),movement:num("humanMovement"),pa:num("humanPA"),pv:num("humanPV"),defense:num("humanDefense"),rd:num("humanRD"),corpo:num("humanCorpo"),foco:num("humanFoco"),nexo:num("humanNexo"),head:num("humanHead"),torso:num("humanTorso"),limb:num("humanLimb"),skills,abilities:Array.isArray(old?.abilities)?old.abilities:[],basicAttack:$("humanBasicAttack").value.trim()||"1d6 + Corpo",strongAttack:$("humanStrongAttack").value.trim()||"2d6 + Corpo",strongAttackLimit:"1/rodada",healthMode:"choice",photo:normalPhoto,woundedPhoto};store(old,x)}
function persistNpc(){const old=threats.find(x=>String(x.id)===String(editingId)),level=Math.max(1,Math.min(3,num("npcLevel"))),x={...(old||{}),id:editingId||"npc-"+Date.now(),preset:false,type:"npc",name:$("npcName").value.trim()||"NPC Aliado",npcRole:$("npcRole").value,npcLevel:level,pv:level*25,size:1,rd:0,defense:0,pa:0,movement:1,attackTraining:[0,"1d4","1d8","1d12"][level],attackBonus:level*2,damage:`${level}d8+${level*2}`,photo:normalPhoto};store(old,x)}
function store(old,x){const index=old?threats.indexOf(old):-1;if(index>=0)threats[index]=x;else threats.push(x);if(!save()){if(index>=0)threats[index]=old;else threats.pop();return}render($("searchEnemy").value);$("enemyModal").classList.add("hidden")}
function deleteCurrentThreat(){if(!editingId||!confirm("Excluir este registro?"))return;threats=threats.filter(x=>String(x.id)!==String(editingId));save();render();$("enemyModal").classList.add("hidden")}
document.addEventListener("DOMContentLoaded",()=>{buildSkills();load();render();$("newEnemy").onclick=()=>open(null,"creature");$("newNpc").onclick=()=>open(null,"npc");$("addEnemyAbility").onclick=addAbilitySlot;$("closeEnemyModal").onclick=()=>$("enemyModal").classList.add("hidden");$("enemyModal").onclick=e=>{if(e.target===$("enemyModal"))$("enemyModal").classList.add("hidden")};$("searchEnemy").oninput=e=>render(e.target.value);$("enemyList").onclick=e=>{const b=e.target.closest("[data-view]");if(b)open(b.dataset.view)};document.querySelectorAll(".enemy-type").forEach(b=>b.onclick=()=>setType(b.dataset.type));["enemyNA","enemyCorpo","enemyFoco","enemyNexo"].forEach(id=>$(id).addEventListener("input",refresh));$("enemySkills").addEventListener("change",refresh);$("npcLevel").addEventListener("change",refreshNpcSummary);$("saveEnemy").onclick=persist;$("saveHuman").onclick=persistHuman;$("saveNpc").onclick=persistNpc;["deleteEnemy","deleteHuman","deleteNpc"].forEach(id=>$(id).onclick=deleteCurrentThreat);$("enemyPhoto").onchange=()=>fileToData($("enemyPhoto"),v=>{normalPhoto=v;setPhotoPreview("enemyPhotoPreview",v,"👹","Foto normal")});$("enemyWoundedPhoto").onchange=()=>fileToData($("enemyWoundedPhoto"),v=>{woundedPhoto=v;setPhotoPreview("enemyWoundedPhotoPreview",v,"👹","Foto machucada")});$("humanPhoto").onchange=()=>fileToData($("humanPhoto"),v=>{normalPhoto=v;setPhotoPreview("humanPhotoPreview",v,"👤","Foto normal")});$("humanWoundedPhoto").onchange=()=>fileToData($("humanWoundedPhoto"),v=>{woundedPhoto=v;setPhotoPreview("humanWoundedPhotoPreview",v,"👤","Foto machucada")});$("npcPhoto").onchange=()=>fileToData($("npcPhoto"),v=>{normalPhoto=v;setPhotoPreview("npcPhotoPreview",v,"♟","Foto do NPC")})});
window.OrdemThreatRules={stats,damage,storageKey:KEY,abilityCatalog:ENEMY_ABILITY_CATALOG,deathGodPreset:deathGod};
})();
