(()=>{"use strict";
const KEY="ordem_threats";
const skillNames=["Manobra","Disciplina","Especialização","Discreto","Interação","Fortitude","Intimidação","Dedução","Luta","Medicina","Ocultismo","Percepção","Pilotagem","Pontaria","Presteza","Sobrevivência","Informação","Vontade","Sorte"];
const wolfSkills={Manobra:2,Discreto:2,Fortitude:2,Intimidação:2,Luta:2,Presteza:3,Percepção:3};
let threats=[],editingId=null,type="creature",normalPhoto="",woundedPhoto="";
const $=id=>document.getElementById(id),num=id=>Math.max(0,Number($(id)?.value)||0);
function load(){try{threats=JSON.parse(localStorage.getItem(KEY)||"[]");if(!Array.isArray(threats))threats=[]}catch{threats=[]}seedWolf()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(threats));return true}catch(error){console.error("Erro ao salvar ameaças:",error);alert("Não foi possível salvar as fotos. Tente imagens menores ou remova imagens antigas.");return false}}
function stats(na){na=Math.max(0,na|0);return{pv:20*(na+1),rd:2*(na+1),defense:5+2*na,attr:2*(na+1),skillBudget:4+2*na,pa:3+Math.floor(na/3),head:4*(na+1),torso:4*(na+1),limb:3*(na+1),movement:2}}
function damage(na,strong=false){let dice;if(na===0)dice="1d4";else if(na===1)dice="1d6";else if(na===2)dice="1d8";else if(na===3)dice="1d10";else if(na===4)dice="1d12";else{const extra=4+2*(na-4);dice="1d12 + 1d"+extra}if(strong)dice=dice.replace(/1d(\d+)/g,"2d$1");return dice+" + Corpo"}
function wolf(){const s=stats(6);return{id:"lobisomem-pronto",systemId:"lobisomem-na6",preset:true,type:"creature",name:"Lobisomem",na:6,element:"Morte",size:2,corpo:6,foco:5,nexo:3,skills:{...wolfSkills},...s,basicAttack:damage(6),strongAttack:damage(6,true),strongAttackLimit:"1/rodada",healthMode:"choice",photo:"",woundedPhoto:""}}
function seedWolf(){const i=threats.findIndex(x=>x.systemId==="lobisomem-na6");const ready=wolf();if(i<0)threats.unshift(ready);else threats[i]={...threats[i],...ready,photo:threats[i].photo||"",woundedPhoto:threats[i].woundedPhoto||""};save()}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function rank(v){return ["Destreinado","Treinado • 1d4","Veterano • 1d8","Especialista • 1d12"][Number(v)||0]}
function render(q=""){const root=$("enemyList"),term=q.trim().toLowerCase(),list=threats.filter(x=>!term||x.name.toLowerCase().includes(term)||String(x.element||"").toLowerCase().includes(term));if(!list.length){root.innerHTML='<div class="empty-enemies"><div class="icon">◇</div><h3>Nenhuma ameaça encontrada</h3><p>Crie uma ameaça para começar.</p></div>';return}root.innerHTML=list.map(x=>'<article class="enemy-card" data-element="'+esc(x.element||"")+'"><div class="enemy-photo">'+(x.photo?'<img src="'+x.photo+'" alt="">':'<span>'+(x.type==="human"?"👤":"👹")+'</span>')+'</div><div class="enemy-info"><h2>'+esc(x.name)+'</h2><p>'+(x.type==="human"?"Humano":esc(x.element)+" • NA "+x.na+" • Tamanho "+x.size)+'</p><p>'+(x.type==="creature"?x.pv+" PV • DEF "+x.defense+" • RD "+x.rd+" • "+x.pa+" PA • MOV "+x.movement:"Ameaça humana")+'</p></div><div class="enemy-buttons"><button class="edit-button" data-view="'+x.id+'">'+(x.preset?"Ver ficha":"Editar")+'</button></div></article>').join("")}
function buildSkills(){ $("enemySkills").innerHTML=skillNames.map(n=>'<label>'+n+'<select data-skill="'+n+'"><option value="0">Destreinado</option><option value="1">Treinado • 1d4</option><option value="2">Veterano • 1d8</option><option value="3">Especialista • 1d12</option></select></label>').join("")}
function refresh(){const na=num("enemyNA"),s=stats(na),used=num("enemyCorpo")+num("enemyFoco")+num("enemyNexo"),su=[...document.querySelectorAll("[data-skill]")].reduce((a,e)=>a+Number(e.value||0),0);$("enemyAutoStats").innerHTML='<b>'+s.pv+'</b><small>PV clássico</small><b>'+s.defense+'</b><small>Defesa</small><b>'+s.rd+'</b><small>RD mundana</small><b>'+s.pa+'</b><small>PA</small><b>'+s.head+'</b><small>Cabeça</small><b>'+s.torso+'</b><small>Torso</small><b>'+s.limb+'</b><small>Cada braço/perna</small><b>2</b><small>Movimento</small>';$("attributeBudget").textContent=used+"/"+s.attr+" pontos";$("skillBudget").textContent=su+"/"+s.skillBudget+" pontos";$("attributeBudget").classList.toggle("over",used>s.attr);$("skillBudget").classList.toggle("over",su>s.skillBudget);$("basicAttack").textContent=damage(na);$("strongAttack").textContent=damage(na,true)+" • 1×/rodada"}
function setType(v){type=v;document.querySelectorAll(".enemy-type").forEach(b=>b.classList.toggle("active",b.dataset.type===v));$("creatureEditor").classList.toggle("hidden",v!=="creature");$("humanEditor").classList.toggle("hidden",v!=="human")}
function setPhotoPreview(id,value,icon,label){$(id).innerHTML=value?'<img src="'+value+'" alt="">':'<span>'+icon+'</span><small>'+label+'</small>'}
function reset(){editingId=null;normalPhoto="";woundedPhoto="";$("enemyModalTitle").textContent="Nova Ameaça";$("enemyName").value="";$("enemyNA").value=0;$("enemyElement").value="Sangue";$("enemySize").value=1;$("enemyCorpo").value=0;$("enemyFoco").value=0;$("enemyNexo").value=0;document.querySelectorAll("[data-skill]").forEach(e=>e.value=0);document.querySelectorAll("#creatureEditor input,#creatureEditor select").forEach(e=>e.disabled=false);$("deleteEnemy").classList.add("hidden");$("saveEnemy").classList.remove("hidden");$("saveEnemy").textContent="Salvar criatura";setPhotoPreview("enemyPhotoPreview","","👹","Foto normal");setPhotoPreview("enemyWoundedPhotoPreview","","👹","Foto machucada");setPhotoPreview("humanPhotoPreview","","👤","Foto normal");setPhotoPreview("humanWoundedPhotoPreview","","👤","Foto machucada");setType("creature");refresh()}
function open(id){reset();if(id){const x=threats.find(t=>String(t.id)===String(id));if(!x)return;editingId=x.id;normalPhoto=x.photo||"";woundedPhoto=x.woundedPhoto||"";$("enemyModalTitle").textContent=x.preset?x.name:"Editar "+x.name;setType(x.type||"creature");if(x.type==="creature"){$("enemyName").value=x.name;$("enemyNA").value=x.na;$("enemyElement").value=x.element;$("enemySize").value=x.size;$("enemyCorpo").value=x.corpo;$("enemyFoco").value=x.foco;$("enemyNexo").value=x.nexo;document.querySelectorAll("[data-skill]").forEach(e=>e.value=x.skills?.[e.dataset.skill]||0);setPhotoPreview("enemyPhotoPreview",normalPhoto,"👹","Foto normal");setPhotoPreview("enemyWoundedPhotoPreview",woundedPhoto,"👹","Foto machucada");refresh();if(x.preset){document.querySelectorAll("#creatureEditor input:not([type=file]),#creatureEditor select").forEach(e=>e.disabled=true);$("saveEnemy").classList.remove("hidden");$("saveEnemy").textContent="Salvar fotos";$("deleteEnemy").classList.add("hidden")}}else fillHuman(x);if(!x.preset)$("deleteEnemy").classList.remove("hidden")}$("enemyModal").classList.remove("hidden")}
function fillHuman(x={}){$("humanName").value=x.name||"";setPhotoPreview("humanPhotoPreview",x.photo||"","👤","Foto normal");setPhotoPreview("humanWoundedPhotoPreview",x.woundedPhoto||"","👤","Foto machucada")}
function fileToData(input,cb){const f=input.files?.[0];if(!f)return;if(f.size>5*1024*1024){alert("A imagem é muito grande. Use uma imagem de até 5 MB.");input.value="";return}const r=new FileReader;r.onerror=()=>alert("Não foi possível ler a imagem.");r.onload=()=>{const image=new Image;image.onerror=()=>alert("A imagem selecionada é inválida.");image.onload=()=>{const scale=Math.min(1,700/image.width,900/image.height),width=Math.max(1,Math.round(image.width*scale)),height=Math.max(1,Math.round(image.height*scale)),canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const context=canvas.getContext("2d");if(!context){alert("Não foi possível processar a imagem.");return}context.drawImage(image,0,0,width,height);cb(canvas.toDataURL("image/webp",.78))};image.src=r.result};r.readAsDataURL(f)}
function persist(){if(type==="human")return persistHuman();const old=threats.find(x=>String(x.id)===String(editingId));if(old?.preset){const beforePhoto=old.photo,beforeWoundedPhoto=old.woundedPhoto;old.photo=normalPhoto;old.woundedPhoto=woundedPhoto;if(!save()){old.photo=beforePhoto;old.woundedPhoto=beforeWoundedPhoto;return}render($("searchEnemy").value);$("enemyModal").classList.add("hidden");return}const na=num("enemyNA"),s=stats(na),attrs=num("enemyCorpo")+num("enemyFoco")+num("enemyNexo"),skills={};document.querySelectorAll("[data-skill]").forEach(e=>skills[e.dataset.skill]=Number(e.value||0));const st=Object.values(skills).reduce((a,b)=>a+b,0);if(attrs>s.attr)return alert("Atributos excedem o limite de "+s.attr+" pontos.");if(st>s.skillBudget)return alert("Perícias excedem o limite de "+s.skillBudget+" pontos.");const x={...(old||{}),id:editingId||"threat-"+Date.now(),preset:false,type:"creature",name:$("enemyName").value.trim()||"Criatura",na,element:$("enemyElement").value,size:Math.max(1,num("enemySize")),corpo:num("enemyCorpo"),foco:num("enemyFoco"),nexo:num("enemyNexo"),skills,...s,basicAttack:damage(na),strongAttack:damage(na,true),strongAttackLimit:"1/rodada",healthMode:"choice",photo:normalPhoto,woundedPhoto};store(old,x)}
function persistHuman(){const old=threats.find(x=>x.id===editingId),x={...(old||{}),id:editingId||"human-threat-"+Date.now(),preset:false,type:"human",name:$("humanName").value.trim()||"Humano",photo:normalPhoto,woundedPhoto};store(old,x)}
function store(old,x){const index=old?threats.indexOf(old):-1;if(index>=0)threats[index]=x;else threats.push(x);if(!save()){if(index>=0)threats[index]=old;else threats.pop();return}render($("searchEnemy").value);$("enemyModal").classList.add("hidden")}
document.addEventListener("DOMContentLoaded",()=>{buildSkills();load();render();$("newEnemy").onclick=()=>open();$("closeEnemyModal").onclick=()=>$("enemyModal").classList.add("hidden");$("enemyModal").onclick=e=>{if(e.target===$("enemyModal"))$("enemyModal").classList.add("hidden")};$("searchEnemy").oninput=e=>render(e.target.value);$("enemyList").onclick=e=>{const b=e.target.closest("[data-view]");if(b)open(b.dataset.view)};document.querySelectorAll(".enemy-type").forEach(b=>b.onclick=()=>setType(b.dataset.type));["enemyNA","enemyCorpo","enemyFoco","enemyNexo"].forEach(id=>$(id).addEventListener("input",refresh));$("enemySkills").addEventListener("change",refresh);$("saveEnemy").onclick=persist;$("saveHuman").onclick=persistHuman;$("deleteEnemy").onclick=()=>{if(!editingId||!confirm("Excluir esta ameaça?"))return;threats=threats.filter(x=>String(x.id)!==String(editingId));save();render();$("enemyModal").classList.add("hidden")};$("enemyPhoto").onchange=()=>fileToData($("enemyPhoto"),v=>{normalPhoto=v;setPhotoPreview("enemyPhotoPreview",v,"👹","Foto normal")});$("enemyWoundedPhoto").onchange=()=>fileToData($("enemyWoundedPhoto"),v=>{woundedPhoto=v;setPhotoPreview("enemyWoundedPhotoPreview",v,"👹","Foto machucada")});$("humanPhoto").onchange=()=>fileToData($("humanPhoto"),v=>{normalPhoto=v;setPhotoPreview("humanPhotoPreview",v,"👤","Foto normal")});$("humanWoundedPhoto").onchange=()=>fileToData($("humanWoundedPhoto"),v=>{woundedPhoto=v;setPhotoPreview("humanWoundedPhotoPreview",v,"👤","Foto machucada")})});
window.OrdemThreatRules={stats,damage,storageKey:KEY};
})();
