(()=>{"use strict";
const KEY="ordem_threats";
const skillNames=["Manobra","Disciplina","Especialização","Discreto","Interação","Fortitude","Intimidação","Dedução","Luta","Medicina","Ocultismo","Percepção","Pilotagem","Pontaria","Presteza","Sobrevivência","Informação","Vontade","Sorte"];
const wolfSkills={Manobra:2,Discreto:2,Fortitude:2,Intimidação:2,Luta:2,Presteza:3,Percepção:3};
let threats=[],editingId=null,type="creature",normalPhoto="",woundedPhoto="";
const $=id=>document.getElementById(id), num=id=>Math.max(0,Number($(id)?.value)||0);
function load(){try{threats=JSON.parse(localStorage.getItem(KEY)||"[]");if(!Array.isArray(threats))threats=[]}catch{threats=[]}seedWolf()}
function save(){localStorage.setItem(KEY,JSON.stringify(threats))}
function stats(na){na=Math.max(0,na|0);return{pv:20*(na+1),rd:2*(na+1),defense:5+2*na,attr:2*(na+1),skills:4+2*na,pa:3+Math.floor(na/3),head:4*(na+1),torso:4*(na+1),limb:3*(na+1),move:2}}
function damage(na,strong=false){let dice;if(na===0)dice="1d4";else if(na===1)dice="1d6";else if(na===2)dice="1d8";else if(na===3)dice="1d10";else if(na===4)dice="1d12";else{const extra=4+2*(na-4);dice="1d12 + 1d"+extra}if(strong)dice=dice.replace(/1d(\d+)/g,"2d$1");return dice+" + Corpo"}
function seedWolf(){if(threats.some(x=>x.systemId==="lobisomem-na6"))return;const s=stats(6);threats.push({id:"lobisomem-"+Date.now(),systemId:"lobisomem-na6",type:"creature",name:"Lobisomem",na:6,element:"Morte",size:2,movement:2,corpo:6,foco:5,nexo:3,skills:{...wolfSkills},...s,basicAttack:damage(6),strongAttack:damage(6,true),strongAttackLimit:"1/rodada",healthMode:"choice",photo:"",woundedPhoto:""});save()}
function render(q=""){const root=$("enemyList"),term=q.trim().toLowerCase();const list=threats.filter(x=>!term||x.name.toLowerCase().includes(term)||x.element.toLowerCase().includes(term));if(!list.length){root.innerHTML='<div class="empty-enemies"><div class="icon">◇</div><h3>Nenhuma ameaça encontrada</h3><p>Crie uma criatura para começar os testes.</p></div>';return}root.innerHTML=list.map(x=>'<article class="enemy-card" data-element="'+x.element+'"><div class="enemy-photo">'+(x.photo?'<img src="'+x.photo+'" alt="">':'<span>👹</span>')+'</div><div class="enemy-info"><h2>'+esc(x.name)+'</h2><p>'+esc(x.element)+' • NA '+x.na+' • Tamanho '+x.size+'</p><p>'+x.pv+' PV • DEF '+x.defense+' • RD '+x.rd+' • '+x.pa+' PA • MOV '+x.movement+'</p></div><div class="enemy-buttons"><button class="edit-button" data-edit="'+x.id+'">Editar</button></div></article>').join("")}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function buildSkills(){const root=$("enemySkills");root.innerHTML=skillNames.map(n=>'<label>'+n+'<select data-skill="'+n+'"><option value="0">Destreinado</option><option value="1">Treinado • 1d4</option><option value="2">Veterano • 1d8</option><option value="3">Especialista • 1d12</option></select></label>').join("")}
function refresh(){const na=num("enemyNA"),s=stats(na),used=num("enemyCorpo")+num("enemyFoco")+num("enemyNexo"),skillUsed=[...document.querySelectorAll("[data-skill]")].reduce((a,e)=>a+Number(e.value||0),0);$("enemyAutoStats").innerHTML='<b>'+s.pv+'</b><small>PV clássico</small><b>'+s.defense+'</b><small>Defesa</small><b>'+s.rd+'</b><small>RD mundana</small><b>'+s.pa+'</b><small>PA</small><b>'+s.head+'</b><small>Cabeça</small><b>'+s.torso+'</b><small>Torso</small><b>'+s.limb+'</b><small>Cada braço/perna</small><b>2</b><small>Movimento</small>';$("attributeBudget").textContent=used+"/"+s.attr+" pontos";$("skillBudget").textContent=skillUsed+"/"+s.skills+" pontos";$("attributeBudget").classList.toggle("over",used>s.attr);$("skillBudget").classList.toggle("over",skillUsed>s.skills);$("basicAttack").textContent=damage(na);$("strongAttack").textContent=damage(na,true)+" • 1×/rodada"}
function setType(v){type=v;document.querySelectorAll(".enemy-type").forEach(b=>b.classList.toggle("active",b.dataset.type===v));$("creatureEditor").classList.toggle("hidden",v!=="creature");$("humanEditor").classList.toggle("hidden",v!=="human")}
function reset(){editingId=null;normalPhoto="";woundedPhoto="";$("enemyModalTitle").textContent="Nova Ameaça";$("enemyName").value="Lobisomem";$("enemyNA").value=6;$("enemyElement").value="Morte";$("enemySize").value=2;$("enemyCorpo").value=6;$("enemyFoco").value=5;$("enemyNexo").value=3;document.querySelectorAll("[data-skill]").forEach(e=>e.value=wolfSkills[e.dataset.skill]||0);$("deleteEnemy").classList.add("hidden");$("enemyPhotoPreview").innerHTML="<span>👹</span><small>Foto normal</small>";setType("creature");refresh()}
function open(id){reset();if(id){const x=threats.find(t=>t.id===id);if(!x)return;editingId=id;normalPhoto=x.photo||"";woundedPhoto=x.woundedPhoto||"";$("enemyModalTitle").textContent="Editar "+x.name;$("enemyName").value=x.name;$("enemyNA").value=x.na;$("enemyElement").value=x.element;$("enemySize").value=x.size;$("enemyCorpo").value=x.corpo;$("enemyFoco").value=x.foco;$("enemyNexo").value=x.nexo;document.querySelectorAll("[data-skill]").forEach(e=>e.value=x.skills?.[e.dataset.skill]||0);$("deleteEnemy").classList.remove("hidden");if(normalPhoto)$("enemyPhotoPreview").innerHTML='<img src="'+normalPhoto+'" alt="">';refresh()}$("enemyModal").classList.remove("hidden")}
function fileToData(input,cb){const f=input.files?.[0];if(!f)return;const r=new FileReader;r.onload=()=>cb(r.result);r.readAsDataURL(f)}
function persist(){const na=num("enemyNA"),s=stats(na),attrs=num("enemyCorpo")+num("enemyFoco")+num("enemyNexo"),skills={};document.querySelectorAll("[data-skill]").forEach(e=>skills[e.dataset.skill]=Number(e.value||0));const skillTotal=Object.values(skills).reduce((a,b)=>a+b,0);if(attrs>s.attr)return alert("Atributos excedem o limite de "+s.attr+" pontos.");if(skillTotal>s.skills)return alert("Perícias excedem o limite de "+s.skills+" pontos.");const old=threats.find(x=>x.id===editingId);const x={...(old||{}),id:editingId||"threat-"+Date.now(),type:"creature",name:$("enemyName").value.trim()||"Criatura",na,element:$("enemyElement").value,size:Math.max(1,num("enemySize")),movement:2,corpo:num("enemyCorpo"),foco:num("enemyFoco"),nexo:num("enemyNexo"),skills,...s,basicAttack:damage(na),strongAttack:damage(na,true),strongAttackLimit:"1/rodada",healthMode:"choice",photo:normalPhoto,woundedPhoto};if(old)threats[threats.indexOf(old)]=x;else threats.push(x);save();render($("searchEnemy").value);$("enemyModal").classList.add("hidden")}
document.addEventListener("DOMContentLoaded",()=>{buildSkills();load();render();$("newEnemy").onclick=()=>open();$("closeEnemyModal").onclick=()=> $("enemyModal").classList.add("hidden");$("enemyModal").onclick=e=>{if(e.target===$("enemyModal"))$("enemyModal").classList.add("hidden")};$("searchEnemy").oninput=e=>render(e.target.value);$("enemyList").onclick=e=>{const b=e.target.closest("[data-edit]");if(b)open(b.dataset.edit)};document.querySelectorAll(".enemy-type").forEach(b=>b.onclick=()=>setType(b.dataset.type));["enemyNA","enemyCorpo","enemyFoco","enemyNexo"].forEach(id=>$(id).addEventListener("input",refresh));$("enemySkills").addEventListener("change",refresh);$("saveEnemy").onclick=persist;$("deleteEnemy").onclick=()=>{if(!editingId||!confirm("Excluir esta ameaça?"))return;threats=threats.filter(x=>x.id!==editingId);save();render();$("enemyModal").classList.add("hidden")};$("openHumanEditor").onclick=()=>location.href="editor-ficha.html";$("enemyPhoto").onchange=()=>fileToData($("enemyPhoto"),v=>{normalPhoto=v;$("enemyPhotoPreview").innerHTML='<img src="'+v+'" alt="">' });$("enemyWoundedPhoto").onchange=()=>fileToData($("enemyWoundedPhoto"),v=>woundedPhoto=v)});
window.OrdemThreatRules={stats,damage,storageKey:KEY};
})();