/*==========================================================
= GRIMÓRIO V2.5 — EDITOR ESTÁVEL + CONJURAR/LANÇAR
==========================================================*/
(function(){
"use strict";
const STORAGE="ordem_characters",DRAFT_KEY="ordem_grimoire_v2_draft";
const ELEMENTS={sangue:{name:"Sangue",color:"#c92b45"},morte:{name:"Morte",color:"#74717d"},energia:{name:"Energia",color:"#39d879"},conhecimento:{name:"Conhecimento",color:"#e0b84f"},medo:{name:"Medo",color:"#e8e8ef"}};
const ACTIONS={
 atormentar:{name:"Atormentar",dt:12,description:"Causa 1d6 de dano do elemento escolhido."},aliviar:{name:"Aliviar",dt:12,description:"Recupera 1d6 PV de um alvo."},transmutar:{name:"Transmutar",dt:12,description:"Cria, altera ou modifica um objeto de acordo com o elemento utilizado."},potencializar:{name:"Potencializar",dt:12,description:"Concede +1 em um atributo pelo tempo do ritual."},resguardar:{name:"Resguardar",dt:12,description:"Concede 5 pontos de RD temporários."},preservar:{name:"Preservar",dt:12,description:"Concede 5 PV temporários."},
 arruinar:{name:"Arruinar",dt:15,description:"Reduz a Defesa do alvo em 3."},devastar:{name:"Devastar",dt:15,description:"Reduz a DT dos testes realizados pelo alvo."},prender:{name:"Prender",dt:15,description:"Em uma falha contra a DT, o alvo fica Imobilizado."},ocultar:{name:"Ocultar",dt:15,description:"Esconde objeto, criatura ou presença paranormal."},silenciar:{name:"Silenciar",dt:15,description:"Impede o alvo de conjurar rituais."},teleportar:{name:"Teleportar",dt:15,description:"Move instantaneamente o conjurador."},
 revelar:{name:"Revelar",dt:18,description:"Descobre uma informação oculta, fraqueza ou efeito ativo."},detectar:{name:"Detectar",dt:18,description:"Detecta criaturas, objetos e fenômenos paranormais."},iludir:{name:"Iludir",dt:18,description:"Cria uma ilusão, clone ou camuflagem caso o teste de conjuração seja bem-sucedido."},selar:{name:"Selar",dt:18,description:"Neutraliza habilidades até permitir o selamento."},invocar:{name:"Invocar",dt:18,description:"Invoca uma criatura previamente selada caso o teste de conjuração seja bem-sucedido."},dissipar:{name:"Dissipar",dt:18,description:"Cancela ou impede um ritual caso o teste de conjuração seja bem-sucedido."}
};
const ENH={canalizar:"Canalizar",propagar:"Propagar",incorporar:"Incorporar",assegurar:"Assegurar",maximizar:"Maximizar",elevar:"Elevar",focar:"Focar",dificultar:"Dificultar",empurrar:"Empurrar",atrair:"Atrair"};
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function read(){try{return JSON.parse(localStorage.getItem(STORAGE)||"[]")}catch{return[]}}
function write(v){localStorage.setItem(STORAGE,JSON.stringify(v));}
function id(){const p=new URLSearchParams(location.search);return p.get("id")||p.get("character")||localStorage.getItem("ordem_table_character");}
function norm(g){g=g&&typeof g==="object"?g:{};return{version:2,elements:Array.isArray(g.elements)?g.elements:[],actions:Array.isArray(g.actions)?g.actions:[],enhancements:g.enhancements||{},rituals:Array.isArray(g.rituals)?g.rituals:[]};}
function getG(){const c=read().find(x=>x.id===id());if(c)return norm(c.grimoireV2||c.grimoire);try{return norm(JSON.parse(sessionStorage.getItem(DRAFT_KEY)||"null"))}catch{return norm({})}}
function saveG(g){g=norm(g);sessionStorage.setItem(DRAFT_KEY,JSON.stringify(g));const list=read(),i=list.findIndex(x=>x.id===id());if(i>=0){list[i].grimoireV2=g;list[i].grimoire=g;write(list);}return g;}
function totalEnh(r){return Object.values(r.enhancements||{}).reduce((a,b)=>a+(Number(b)||0),0)}
function calc(action,enh){let dice=1,die=6,flat=0,targets=1;const n=k=>Number(enh[k])||0;dice+=n("canalizar");die=[6,8,10,12][Math.min(3,n("focar"))];dice*=Math.pow(2,n("maximizar"));flat=n("assegurar")*4;targets+=n("propagar");return{formula:["atormentar","aliviar"].includes(action)?`${dice}d${die}${flat?` + ${flat}`:""}`:"",targets};}
function renderEditor(){const old=document.querySelector("#addRitualEditor")?.closest("section.editor-section-card")||document.querySelector("section[data-grim-v2]");if(!old||old.dataset.grim25)return;old.dataset.grim25="1";const g=getG();let selectedElement="",selectedAction="",uses={};
 const manager=()=>`<div class="g25-manager"><h3>Gerenciar palavras aprendidas</h3><div class="g25-grid">${Object.entries(ELEMENTS).map(([k,v])=>`<label><input type="checkbox" data-learn-el="${k}" ${g.elements.includes(k)?"checked":""}><b>${v.name}</b></label>`).join("")}</div><div class="g25-grid g25-actions-learn">${Object.entries(ACTIONS).map(([k,v])=>`<label><input type="checkbox" data-learn-act="${k}" ${g.actions.includes(k)?"checked":""}><span><b>${v.name}</b><small>DT ${v.dt}</small></span></label>`).join("")}</div><div class="g25-enh-learn">${Object.entries(ENH).map(([k,v])=>`<div><span><b>${v}</b><small>Aprendido ×<i data-learn-count="${k}">${Number(g.enhancements[k])||0}</i></small></span><button data-learn-minus="${k}">−</button><button data-learn-plus="${k}">+</button></div>`).join("")}</div></div>`;
 old.innerHTML=`<div class="g25-wrap">${manager()}<div class="g25-builder"><div class="section-heading"><span class="section-label">GRIMÓRIO</span><h2>Construir Ritual</h2></div><label class="g25-name">Nome do ritual<input id="g25Name" placeholder="Nome personalizado"></label><div class="g25-step"><b>1. Escolha o elemento</b><div id="g25Elements" class="g25-cards"></div></div><div id="g25ActionStep" class="g25-step hidden"><b>2. Escolha a ação</b><div id="g25Actions" class="g25-cards action"></div></div><div id="g25EnhStep" class="g25-step hidden"><b>3. Aprimoramentos</b><div id="g25Enh" class="g25-enh-use"></div></div><div id="g25Preview" class="g25-preview">Escolha um elemento.</div><button id="g25Save" class="primary-button" disabled>Salvar Ritual</button></div><div class="g25-saved"><h3>Rituais salvos</h3><div id="g25Saved"></div></div></div>`;
 function drawElements(){const root=old.querySelector("#g25Elements");root.innerHTML=g.elements.map(k=>`<button data-pick-el="${k}" style="--ec:${ELEMENTS[k].color}">${ELEMENTS[k].name}</button>`).join("")||"<p>Nenhum elemento aprendido.</p>";root.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedElement=b.dataset.pickEl;selectedAction="";uses={};old.querySelector(".g25-builder").style.setProperty("--accent",ELEMENTS[selectedElement].color);drawElements();drawActions();preview();});}
 function drawActions(){const step=old.querySelector("#g25ActionStep"),root=old.querySelector("#g25Actions");step.classList.toggle("hidden",!selectedElement);root.innerHTML=g.actions.map(k=>`<button data-pick-act="${k}" class="${selectedAction===k?"active":""}"><b>${ACTIONS[k].name}</b><small>${ACTIONS[k].description}</small><i>DT ${ACTIONS[k].dt}</i></button>`).join("");root.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedAction=b.dataset.pickAct;uses={};drawActions();drawEnh();preview();});}
 function drawEnh(){const step=old.querySelector("#g25EnhStep"),root=old.querySelector("#g25Enh");step.classList.toggle("hidden",!selectedAction);root.innerHTML=Object.entries(ENH).filter(([k])=>(Number(g.enhancements[k])||0)>0).map(([k,v])=>`<div><span><b>${v}</b><small>Disponível ×${g.enhancements[k]}</small></span><button data-use-minus="${k}">−</button><i>${uses[k]||0}</i><button data-use-plus="${k}">+</button></div>`).join("")||"<p>Nenhum aprimoramento aprendido.</p>";root.querySelectorAll("[data-use-plus]").forEach(b=>b.onclick=()=>{const k=b.dataset.usePlus;uses[k]=Math.min(Number(g.enhancements[k])||0,(uses[k]||0)+1);drawEnh();preview();});root.querySelectorAll("[data-use-minus]").forEach(b=>b.onclick=()=>{const k=b.dataset.useMinus;uses[k]=Math.max(0,(uses[k]||0)-1);drawEnh();preview();});}
 function preview(){const p=old.querySelector("#g25Preview"),btn=old.querySelector("#g25Save");if(!selectedElement){p.textContent="Escolha um elemento.";btn.disabled=true;return}if(!selectedAction){p.innerHTML=`<b>${ELEMENTS[selectedElement].name}</b><p>Agora escolha uma palavra de ação.</p>`;btn.disabled=true;return}const c=calc(selectedAction,uses),count=Object.values(uses).reduce((a,b)=>a+(Number(b)||0),0),pm=2+count;p.innerHTML=`<h3>${esc(old.querySelector("#g25Name").value||"Ritual sem nome")}</h3><p><b>${ELEMENTS[selectedElement].name}</b> • ${ACTIONS[selectedAction].name}</p><p>DT ${ACTIONS[selectedAction].dt} • 3 PA • ${pm} PM • ${c.targets} alvo(s)</p>${c.formula?`<p>Efeito: ${c.formula}</p>`:""}<small>${Object.entries(uses).filter(([,n])=>n).map(([k,n])=>`${ENH[k]} ×${n}`).join(" • ")||"Sem aprimoramentos"}</small>`;btn.disabled=false;}
 function saved(){const r=old.querySelector("#g25Saved");r.innerHTML=g.rituals.length?g.rituals.map((x,i)=>`<article style="--ec:${ELEMENTS[x.element]?.color||"#7b2cff"}"><div><b>${esc(x.name)}</b><p>${ELEMENTS[x.element]?.name||x.element} • ${ACTIONS[x.action]?.name||x.action} • DT ${ACTIONS[x.action]?.dt||x.dt||12}</p></div><button data-del="${i}">Excluir</button></article>`).join(""):"<p>Nenhum ritual salvo.</p>";r.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{g.rituals.splice(Number(b.dataset.del),1);saveG(g);saved();});}
 old.querySelectorAll("[data-learn-el]").forEach(i=>i.onchange=()=>{g.elements=Array.from(old.querySelectorAll("[data-learn-el]:checked")).map(x=>x.dataset.learnEl);saveG(g);drawElements();});old.querySelectorAll("[data-learn-act]").forEach(i=>i.onchange=()=>{g.actions=Array.from(old.querySelectorAll("[data-learn-act]:checked")).map(x=>x.dataset.learnAct);saveG(g);drawActions();});old.querySelectorAll("[data-learn-plus]").forEach(b=>b.onclick=()=>{const k=b.dataset.learnPlus;g.enhancements[k]=(Number(g.enhancements[k])||0)+1;old.querySelector(`[data-learn-count="${k}"]`).textContent=g.enhancements[k];saveG(g);drawEnh();});old.querySelectorAll("[data-learn-minus]").forEach(b=>b.onclick=()=>{const k=b.dataset.learnMinus;g.enhancements[k]=Math.max(0,(Number(g.enhancements[k])||0)-1);old.querySelector(`[data-learn-count="${k}"]`).textContent=g.enhancements[k];saveG(g);drawEnh();});old.querySelector("#g25Name").oninput=preview;old.querySelector("#g25Save").onclick=()=>{const name=old.querySelector("#g25Name").value.trim();if(!name||!selectedElement||!selectedAction)return alert("Preencha o nome, elemento e ação.");const c=calc(selectedAction,uses);g.rituals.push({id:`ritual_${Date.now()}`,name,element:selectedElement,action:selectedAction,enhancements:{...uses},dt:ACTIONS[selectedAction].dt,costPA:3,costPM:2+Object.values(uses).reduce((a,b)=>a+(Number(b)||0),0),calculated:{...c,dt:ACTIONS[selectedAction].dt}});saveG(g);old.querySelector("#g25Name").value="";selectedElement="";selectedAction="";uses={};drawElements();drawActions();drawEnh();preview();saved();};drawElements();drawActions();drawEnh();preview();saved();addStyle();}
function skillOcultismo(c){const list=Array.isArray(c?.skills)?c.skills:Object.values(c?.skills||{});const s=list.find(x=>String(x.name||x.id||"").toLowerCase().includes("ocult"))||{};const die=String(s.trainingDie||s.die||s.training||"").match(/d(4|8|12)/i)?.[1];return{die:die?Number(die):0,bonus:Number(s.bonus)||0,penalty:Number(s.penalty)||0,attribute:Number(c?.attributes?.nexo??c?.nexo??1)||0};}
function rollDie(s){return Math.floor(Math.random()*s)+1}
function saveCharacter(c){const list=read(),i=list.findIndex(x=>x.id===c.id);if(i>=0){list[i]=c;write(list);}if(typeof currentTableCharacter!=="undefined"&&currentTableCharacter?.id===c.id)currentTableCharacter=c;}
function state(){currentTableCampaign.combat=currentTableCampaign.combat||{};currentTableCampaign.combat.grimoirePrepared=currentTableCampaign.combat.grimoirePrepared||{};return currentTableCampaign.combat.grimoirePrepared;}
function notify(title,detail){if(!currentTableCampaign)return;currentTableCampaign.actionNotification={id:`grim_${Date.now()}`,kind:"Ritual",icon:"✦",title,detail,createdAt:Date.now()};saveTableCampaign?.();}
function conjure(r){const c=currentTableCharacter;if(!c)return;const st=c.status||(c.status={}),pa=Number(st.paAtual)||0,pm=Number(st.pmAtual??st.pdAtual)||0,costPA=3,costPM=2+totalEnh(r);if(pa<costPA||pm<costPM){addSystemChatMessage?.(`Recursos insuficientes: precisa de ${costPA} PA e ${costPM} PM.`);return}st.paAtual=pa-costPA;st.pmAtual=pm-costPM;st.pdAtual=st.pmAtual;saveCharacter(c);const sk=skillOcultismo(c),d12=rollDie(12),train=sk.die?rollDie(sk.die):0,total=d12+train+sk.attribute+sk.bonus-sk.penalty,dt=ACTIONS[r.action]?.dt||r.dt||12,ok=total>=dt;addRollChatMessage?.(`Conjuração • ${r.name}`,`1d12${sk.die?` + 1d${sk.die}`:""} + Nexo`,total,`d12 [${d12}]${sk.die?` + treino [${train}]`:""} + ${sk.attribute} + ${sk.bonus} - ${sk.penalty}`,{rollKind:"ritual-conjuration",ritualId:r.id,success:ok,dt});if(ok){state()[c.id]={ritualId:r.id,preparedAt:Date.now()};saveTableCampaign?.();notify(`${c.name||"O personagem"} conjurou ${r.name}`,`Sucesso no teste de Ocultismo contra DT ${dt}.`);}else notify(`${c.name||"O personagem"} falhou ao conjurar ${r.name}`,`Resultado ${total} contra DT ${dt}.`);openGrimoirePanelV25();}
function targets(){const a=[];(currentTableCampaign?.players||[]).forEach(x=>a.push({id:x.characterId||x.id,name:x.name||"Jogador",type:"player"}));(currentTableCampaign?.enemies||[]).forEach(x=>a.push({id:x.id,name:x.name||"Ameaça",type:"enemy"}));(currentTableCampaign?.npcs||[]).forEach(x=>a.push({id:x.id,name:x.name||"NPC",type:"npc"}));return a;}
function launch(r){const prep=state()[currentTableCharacter.id];if(!prep||prep.ritualId!==r.id)return;const max=Math.max(1,r.calculated?.targets||calc(r.action,r.enhancements||{}).targets);const list=targets();openTablePanel("RITUAL",`Lançar ${r.name}`,`<div class="table-panel-list"><p>Escolha até ${max} alvo(s).</p>${list.map(x=>`<label class="table-panel-card"><input type="checkbox" data-g25-target="${esc(x.id)}"> ${esc(x.name)}</label>`).join("")}<button id="g25ConfirmLaunch" class="primary-button">Lançar ritual</button></div>`);document.getElementById("g25ConfirmLaunch")?.addEventListener("click",()=>{const chosen=Array.from(document.querySelectorAll("[data-g25-target]:checked")).slice(0,max).map(x=>x.parentElement.textContent.trim());if(!chosen.length)return alert("Escolha ao menos um alvo.");delete state()[currentTableCharacter.id];saveTableCampaign?.();const formula=r.calculated?.formula||calc(r.action,r.enhancements||{}).formula;if(formula&&typeof rollDiceExpression==="function"){const rr=rollDiceExpression(formula);addRollChatMessage?.(`${r.action==="aliviar"?"Cura":"Ritual"} • ${r.name}`,formula,rr.total,rr.detail||"",{rollKind:r.action==="aliviar"?"healing":"ritual",ritualId:r.id,targets:chosen});}addSystemChatMessage?.(`${currentTableCharacter.name||"O personagem"} lançou ${r.name} em ${chosen.join(", ")}.`);notify(`${currentTableCharacter.name||"O personagem"} lançou ${r.name}`,chosen.join(", "));openGrimoirePanelV25();});}
function openGrimoirePanelV25(){if(typeof syncCurrentTableCharacterV2==="function")syncCurrentTableCharacterV2();const g=norm(currentTableCharacter?.grimoireV2||currentTableCharacter?.grimoire),prep=state()[currentTableCharacter?.id];openTablePanel("GRIMÓRIO","Rituais",`<div class="table-panel-list">${g.rituals.length?g.rituals.map(r=>{const ready=prep?.ritualId===r.id;return`<div class="table-panel-card" style="border-color:${ELEMENTS[r.element]?.color||"#7b2cff"}"><h3>${esc(r.name)}</h3><p>${ELEMENTS[r.element]?.name||r.element} • ${ACTIONS[r.action]?.name||r.action}</p><p>DT ${ACTIONS[r.action]?.dt||r.dt||12} • 3 PA • ${2+totalEnh(r)} PM</p><div class="g25-table-buttons"><button data-conjure="${r.id}" class="primary-button">Conjurar</button><button data-launch="${r.id}" class="secondary-button" ${ready?"":"disabled"}>Lançar</button></div></div>`}).join(""):"<p>Nenhum ritual salvo.</p>"}</div>`);document.querySelectorAll("[data-conjure]").forEach(b=>b.onclick=()=>conjure(g.rituals.find(r=>r.id===b.dataset.conjure)));document.querySelectorAll("[data-launch]").forEach(b=>b.onclick=()=>launch(g.rituals.find(r=>r.id===b.dataset.launch)));}
function addStyle(){if(document.getElementById("g25Style"))return;const s=document.createElement("style");s.id="g25Style";s.textContent=`.g25-wrap{display:grid;gap:22px}.g25-manager,.g25-builder,.g25-saved{background:#111119;border:1px solid #313142;border-radius:18px;padding:20px}.g25-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:9px;margin:12px 0}.g25-grid label,.g25-enh-learn>div,.g25-enh-use>div{display:flex;align-items:center;gap:9px;padding:11px;border:1px solid #343443;border-radius:12px;background:#171720}.g25-actions-learn label span{display:flex;justify-content:space-between;width:100%}.g25-enh-learn,.g25-enh-use{display:grid;gap:8px}.g25-enh-learn>div,.g25-enh-use>div{justify-content:space-between}.g25-enh-learn span,.g25-enh-use span{display:flex;flex-direction:column;flex:1}.g25-enh-learn button,.g25-enh-use button{width:34px;height:34px}.g25-builder{--accent:#7b2cff;border-color:var(--accent);box-shadow:0 0 30px color-mix(in srgb,var(--accent) 15%,transparent)}.g25-name{display:grid;gap:6px}.g25-step{margin-top:18px}.g25-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:10px;margin-top:10px}.g25-cards button{padding:16px;border:1px solid #39394a;border-radius:14px;background:#171720;color:white;text-align:left}.g25-cards button:hover,.g25-cards button.active{border-color:var(--accent);box-shadow:0 0 18px color-mix(in srgb,var(--accent) 20%,transparent)}.g25-cards button[data-pick-el]{border-color:var(--ec)}.g25-cards.action small,.g25-cards.action i{display:block;margin-top:6px}.g25-preview{margin:18px 0;padding:16px;border-radius:14px;background:#171720;border:1px solid var(--accent)}.g25-saved article{display:flex;justify-content:space-between;align-items:center;padding:14px;border-left:4px solid var(--ec);background:#171720;border-radius:12px;margin-top:9px}.g25-table-buttons{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hidden{display:none!important}`;document.head.appendChild(s);}
function install(){addStyle();if(document.querySelector(".character-editor-page"))renderEditor();if(document.querySelector(".table-app")){window.openGrimoirePanel=openGrimoirePanelV25;window.openGrimoirePanelV25=openGrimoirePanelV25;}}
const t=setInterval(()=>{install();if((document.querySelector(".character-editor-page")&&document.querySelector("[data-grim25]"))||document.querySelector(".table-app"))clearInterval(t)},150);setTimeout(install,0);
})();