/* INVENTÁRIO V1 — armas, modificações, durabilidade, equipamentos e consumíveis */
(function(){"use strict";
const STORE="ordem_characters";
const MELEE={"Faca":["1d4 + CORPO","x2","Corte","Arremessável",1],"Adaga":["1d6 + CORPO","x2","Corte","",1],"Taco":["1d6 + CORPO","x2","Impacto","Bloqueável",2],"Lança":["1d6 + CORPO","x2","Perfuração","Arremessável",2],"Marreta":["2d8 + CORPO","x3","Impacto","",3],"Bastão":["1d6 + CORPO","x2","Impacto","Ataque Duplo",2],"Nunchaku":["1d6 + CORPO","x2","Impacto","Ataque Triplo",2],"Machadinha":["1d6 + CORPO","x3","Corte","Arremessável",2],"Machado":["1d8 + CORPO","x3","Corte","Bloqueável",3],"Espada":["1d10 + CORPO","x2","Corte","Bloqueável",3],"Maça":["2d6 + CORPO","x2","Impacto","",2],"Florete":["1d6 + CORPO","x3","Corte","Ultrapassar",2],"Katana":["1d10 + CORPO","x2","Corte","Saque Rápido",3],"Acha":["1d12 + CORPO","x2","Corte","Demolir",3],"Gadanho":["2d4 + CORPO","x4","Corte","",2],"Motosserra":["3d6 + CORPO","x3","Corte","Acerto Múltiplo",3],"Montante":["2d8 + CORPO","x2","Corte","Bloqueável+",2],"Corrente":["1d8 + CORPO","x2","Impacto","Acorrentar",1]};
const RANGED={"Arco curto":["1d6 + 1","x2","Perfuração","",2,"1–4"],"Arco composto":["1d8 + 2","x2","Perfuração","",3,"1–5"],"Arco refinado":["1d10 + 2","x3","Perfuração","",4,"1–6"],"Besta":["1d6 + 2","x2","Perfuração","",2,"1–4"],"Besta refinada":["1d8 + 3","x2","Perfuração","",3,"1–5"],"Pistola":["1d8","x3","Balístico","",2,"1–5"],"Revólver":["1d8 + 2","x3","Balístico","",2,"1–4"],"Fuzil de caça":["2d8","x2","Balístico","Fardo",3,"1–5"],"Submetralhadora":["2d6","x2","Balístico","Acerto Múltiplo",3,"1–4"],"Espingarda":["4d6","x3","Balístico","",4,"1–3"],"Fuzil de assalto":["2d8","x3","Balístico","",4,"1–5"],"Fuzil de precisão":["2d10","x3","Balístico","Fardo",4,"1–6"],"Metralhadora":["2d12","x3","Balístico","Acerto Múltiplo / Fardo",4,"1–5"],"Lança-chamas":["6d6","x2","Fogo","Labareda / Fardo",5,"1–3"],"Bazuca":["10d8","x2","Fogo","Detonação / Fardo",5,"1–6"]};
const DEF={"Proteção Leve":[3,2],"Proteção Pesada":[5,4],"Escudo":[2,2],"Escudo Grande":[4,3]};
const GENERAL={"Vestimenta":["+2 em uma perícia permitida",1,"equip"],"Soqueira":["+2 em dano desarmado",.5,"equip"],"Kit Médico":["5 usos: +3 Medicina ou 2 usos para curar 5 PV",2,"use",5],"Kit de Reparos":["5 usos: restaura 2 de durabilidade ou item quebrado com 1",2,"use",5],"Cicatrizante":["Restaura 2d6 + 2 PV",1,"use",1],"Binóculos":["+3 em Percepção",1,"equip"],"Pé de Cabra":["+3 para arrombar portas; pode ser usado como bastão",1,"equip"],"Mochila":["+4 EP e –2 Furtividade",0,"equip"],"Bolsa":["+2 EP e –1 Furtividade",0,"equip"]};
const FOOD={"Lanchinho":[3,1,.5],"Lanche":[5,2,1],"Marmita":[7,3,2],"Banquete":[10,4,3]};
const MODM={Certeira:"+2 Ataque",Cruel:"+2 Dano",Discreta:"+3 Ocultar",Perigosa:"+1 Margem de crítico",Eletrificada:"+1d6 Energia",Espinhosa:"+1d4 Perfuração",Resistente:"+3 Durabilidade",Pesada:"+2 dados de dano / +1 PA",Perfurante:"Ignora 5 RD"};
const MODR={Alongada:"+2 Ataque","Calibre Grosso":"+1 dado de dano","Pente Rápido":"Anula Fardo",Discreta:"+3 Ocultar","Mira Laser":"+1 Margem de crítico","Mira Telescópica":"+1 alcance","Visão de Calor":"Ignora camuflagem",Silenciador:"Remove penalidade de Furtividade",Explosiva:"+2d6 no primeiro disparo",Letal:"+1 multiplicador crítico"};
const DUR=new Set(["Bloqueável","Bloqueável+","Acorrentar","Ultrapassar","Demolir","Labareda"]);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let items=[];
function oldChar(){return typeof editingCharacter!=="undefined"?editingCharacter:null}
function normalize(x){x={...x};x.id=x.id||`item_${Date.now()}_${Math.random().toString(36).slice(2)}`;x.mods=Array.isArray(x.mods)?x.mods:[];if(x.maxDur==null&&x.durabilityMax!=null)x.maxDur=x.durabilityMax;if(x.dur==null&&x.durability!=null)x.dur=x.durability;return x}
function load(){items=(Array.isArray(oldChar()?.inventory)?oldChar().inventory:[]).map(normalize)}
function maxDur(i){return (i.baseDur||0)+(i.mods.includes("Resistente")?3:0)}
function damage(i){let d=i.damage||"";if(i.mods.includes("Cruel"))d+=` + 2`;if(i.mods.includes("Eletrificada"))d+=` + 1d6 Energia`;if(i.mods.includes("Espinhosa"))d+=` + 1d4 Perfuração`;return d}
function attack(i){return (i.mods.includes("Certeira")||i.mods.includes("Alongada"))?2:0}
function specialtyButtons(i){return String(i.effect||"").split("/").map(x=>x.trim()).filter(x=>DUR.has(x)).map(x=>`<button type="button" data-special="${esc(x)}" data-id="${i.id}" ${maxDur(i)&&i.dur<=0?'disabled':''}>${esc(x)}</button>`).join("")}
function weaponCard(i){const md=i.kind==="melee"?MODM:MODR,m=maxDur(i),broken=m&&i.dur<=0;return `<article class="inv-card ${broken?'broken':''}"><div class="inv-top"><div><small>${i.kind==='melee'?'ARMA CORPO A CORPO':'ARMA À DISTÂNCIA'}</small><h3>${esc(i.name)}</h3></div><b>${i.ep} EP</b></div><div class="inv-stats"><span>Dano <b>${esc(damage(i))}</b></span>${attack(i)?`<span>Ataque <b>+${attack(i)}</b></span>`:''}<span>Crítico <b>${esc(i.critical)}</b></span><span>${esc(i.type)}</span>${i.range?`<span>Alcance <b>${esc(i.range)}</b></span>`:''}</div>${i.effect?`<p class="inv-effect"><b>${esc(i.effect)}</b></p>`:''}${m?`<div class="inv-dur"><span>Durabilidade</span><b>${i.dur}/${m}${broken?' • QUEBRADO':''}</b><progress max="${m}" value="${Math.max(0,i.dur)}"></progress></div>`:''}<div class="inv-actions">${specialtyButtons(i)}</div><details class="inv-mods"><summary>Modificações (${i.mods.length})</summary><div class="inv-mod-grid">${Object.entries(md).map(([n,e])=>`<label><input type="checkbox" data-mod="${esc(n)}" data-id="${i.id}" ${i.mods.includes(n)?'checked':''}><span><b>${esc(n)}</b><small>${esc(e)}</small></span></label>`).join("")}</div></details><button class="inv-remove" type="button" data-remove="${i.id}">Excluir</button></article>`}
function otherCard(i){let action='';if(i.kind==='defense')action=`<button data-equip="${i.id}">${i.equipped?'Desequipar':'Equipar'}</button>`;if(i.kind==='general')action=`<button data-${i.mode==='equip'?'equip':'use'}="${i.id}">${i.mode==='equip'?(i.equipped?'Desequipar':'Equipar'):'Usar'}</button>`;if(i.kind==='food')action=`<button data-consume="${i.id}">Consumir</button>`;return `<article class="inv-card"><div class="inv-top"><div><small>${i.kind==='defense'?'DEFENSIVO':i.kind==='food'?'ALIMENTO':'ITEM GERAL'}</small><h3>${esc(i.name)}</h3></div><b>${i.ep||0} EP</b></div><p>${esc(i.description||'')}</p>${i.uses!=null?`<div class="inv-dur"><span>Usos</span><b>${i.uses}/${i.maxUses}</b></div>`:''}<div class="inv-actions">${action}</div><button class="inv-remove" data-remove="${i.id}">Excluir</button></article>`}
function ep(){return items.reduce((a,i)=>a+(Number(i.ep)||0),0)}
function render(){const root=document.getElementById('inventoryEditorList');if(!root)return;const corpo=Number(document.getElementById('attributeFOR')?.value)||1,bonus=items.filter(i=>i.equipped&&i.name==='Mochila').length*4+items.filter(i=>i.equipped&&i.name==='Bolsa').length*2,limit=8+corpo+bonus;root.innerHTML=`<div class="inv-toolbar"><div><b>Espaço ${ep()} / ${limit} EP</b><small>8 + CORPO + bônus de itens</small></div><button type="button" id="invAdd">+ Adicionar item</button></div><div class="inv-grid">${items.length?items.map(i=>i.kind==='melee'||i.kind==='ranged'?weaponCard(i):otherCard(i)).join(''):'<div class="editor-empty-state"><span>▣</span><p>Nenhum item adicionado.</p></div>'}</div>`;bind(root)}
function chooser(){const groups=[['Corpo a Corpo',MELEE],['À Distância',RANGED],['Defensivos',DEF],['Itens Gerais',GENERAL],['Alimentos',FOOD]];const box=document.createElement('div');box.className='inv-picker';box.innerHTML=`<div class="inv-picker-box"><header><h2>Adicionar ao Inventário</h2><button data-close>×</button></header>${groups.map(([g,o])=>`<h3>${g}</h3><div class="inv-picks">${Object.keys(o).map(n=>`<button data-pick="${esc(n)}" data-group="${g}">${esc(n)}</button>`).join('')}</div>`).join('')}</div>`;document.body.appendChild(box);box.querySelector('[data-close]').onclick=()=>box.remove();box.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{add(b.dataset.pick,b.dataset.group);box.remove()})}
function add(n,g){let i={id:`item_${Date.now()}_${Math.random().toString(36).slice(2)}`,name:n,mods:[],equipped:false};if(g==='Corpo a Corpo'||g==='À Distância'){const a=(g==='Corpo a Corpo'?MELEE:RANGED)[n];Object.assign(i,{kind:g==='Corpo a Corpo'?'melee':'ranged',damage:a[0],critical:a[1],type:a[2],effect:a[3],ep:a[4],range:a[5]||'',baseDur:String(a[3]).split('/').some(x=>DUR.has(x.trim()))?5:0});i.dur=i.baseDur}else if(g==='Defensivos'){Object.assign(i,{kind:'defense',description:`+${DEF[n][0]} Defesa`,defense:DEF[n][0],ep:DEF[n][1]})}else if(g==='Itens Gerais'){const a=GENERAL[n];Object.assign(i,{kind:'general',description:a[0],ep:a[1],mode:a[2],uses:a[3],maxUses:a[3]})}else{const a=FOOD[n];Object.assign(i,{kind:'food',description:`Recupera ${a[0]} PV e ${a[1]} PM`,healPV:a[0],healPM:a[1],ep:a[2]})}items.push(i);render()}
function bind(root){root.querySelector('#invAdd')?.addEventListener('click',chooser);root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{items=items.filter(i=>i.id!==b.dataset.remove);render()});root.querySelectorAll('[data-mod]').forEach(c=>c.onchange=()=>{const i=items.find(x=>x.id===c.dataset.id),before=maxDur(i);if(c.checked)i.mods.push(c.dataset.mod);else i.mods=i.mods.filter(x=>x!==c.dataset.mod);const after=maxDur(i);i.dur=Math.max(0,Math.min(after,(Number(i.dur)||0)+(after-before)));render()});root.querySelectorAll('[data-special]').forEach(b=>b.onclick=()=>{const i=items.find(x=>x.id===b.dataset.id);if(maxDur(i)){i.dur=Math.max(0,i.dur-1);render()}});root.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{const i=items.find(x=>x.id===b.dataset.equip);i.equipped=!i.equipped;render()});root.querySelectorAll('[data-consume]').forEach(b=>b.onclick=()=>{items=items.filter(x=>x.id!==b.dataset.consume);render()});root.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const i=items.find(x=>x.id===b.dataset.use);if(i.uses>0)i.uses--;render()})}
function install(){const root=document.getElementById('inventoryEditorList');if(!root)return;load();document.getElementById('addInventoryEditor')?.remove();render();const save=document.getElementById('saveCharacterEditor');save?.addEventListener('click',()=>{if(typeof editingCharacter!=='undefined'&&editingCharacter)editingCharacter.inventory=JSON.parse(JSON.stringify(items))},true)}
const style=document.createElement('style');style.textContent=`#inventoryEditorList{display:block}.inv-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:15px;padding:13px;border:1px solid #37313f;border-radius:13px;background:#0d0b11}.inv-toolbar small{display:block;color:#8e8795;margin-top:3px}.inv-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}.inv-card{position:relative;padding:15px;border:1px solid #37313f;border-radius:15px;background:linear-gradient(145deg,#15111a,#0b090e);overflow:hidden}.inv-card.broken{opacity:.62;border-color:#8e3434}.inv-top{display:flex;justify-content:space-between;gap:12px}.inv-top small{color:#8d5cff;font-weight:800;letter-spacing:.1em}.inv-top h3{margin:4px 0 8px}.inv-stats{display:flex;gap:6px;flex-wrap:wrap}.inv-stats span,.inv-effect{padding:5px 8px;border:1px solid #39333f;border-radius:999px;font-size:.78rem}.inv-dur{display:grid;grid-template-columns:1fr auto;gap:5px;margin:12px 0}.inv-dur progress{grid-column:1/-1;width:100%}.inv-actions{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.inv-actions button,.inv-toolbar button{padding:9px 12px;border-radius:9px;border:1px solid #6547a1;background:#2a1c42;color:#fff}.inv-mods{margin-top:10px;border-top:1px solid #2d2931;padding-top:10px}.inv-mod-grid{display:grid;gap:6px;margin-top:9px}.inv-mod-grid label{display:flex;gap:9px;align-items:center;padding:8px;border:1px solid #302b35;border-radius:9px}.inv-mod-grid small{display:block;color:#8f8998}.inv-remove{margin-top:10px;background:transparent;border:0;color:#9a6060}.inv-picker{position:fixed;inset:0;z-index:9999;background:#000b;display:grid;place-items:center;padding:20px}.inv-picker-box{width:min(780px,96vw);max-height:88vh;overflow:auto;background:#100d14;border:1px solid #493d58;border-radius:18px;padding:18px}.inv-picker-box header{display:flex;justify-content:space-between}.inv-picker-box header button{font-size:1.5rem}.inv-picks{display:flex;flex-wrap:wrap;gap:7px}.inv-picks button{padding:8px 10px;border:1px solid #39323f;border-radius:9px;background:#18131e;color:#ddd}`;document.head.appendChild(style);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();})();